### ISSUE TITLE
Minimum width of borders is too thick

### ISSUE THREAD

**Issue by kwkbtr** [Trimmarks/versatype-issues#13]
The minimum width of borders rendered in PDF is 1px=0.75pt=0.265mm, which is too thick for printing.
The unit of border width is also 1px, which means that the next thicker width is 2px=1.5pt=0.53mm.
Borders with intermediate width (0.1mm, 0.2mm, 0.3mm etc.) are required for high quality printing.

Related Chromium issue: [Borders/outlines rounded down, other browsers round up](https://code.google.com/p/chromium/issues/detail?id=229428)

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#419

**Comment by skoji** [comment]
Fixed this in 2018.7 release of VersaType Converter.
