### ISSUE TITLE
Empty last page generated

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#28]
See 

https://print-css.rocks/lesson-positioning.html

**Comment by kwkbtr** [comment]
This is a bug. cf. vivliostyle/vivliostyle.js#97

**Comment by kwkbtr** [comment]
This is fixed in the master of the core engine. It will be in the next Formatter release.

**Comment by kwkbtr** [comment]
Fixed in 2016.4 release.
