### ISSUE TITLE
Table spanning several pages with different table withs looks funny.

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#33]
The table in this test spans several pages. The width of the table on each page is obviously calculated individually per page instead as a whole. As result the overall layout looks funny. This can be solved using a fixed width for the table on the CSS layer...not sure if this counts as bug.

[vivliostyle-output.pdf](https://github.com/vivliostyle/vivliostyle-formatter-issues/files/104867/vivliostyle-output.pdf)

**Comment by kwkbtr** [comment]
The current behavior is not a desirable behavior and we want to fix it.
I created an issue for this on the core engine's repo: vivliostyle/vivliostyle.js#157

**Comment by kwkbtr** [comment]
Fixed in 2017.2.
