### ISSUE TITLE
Improper rendering (related to css float)?

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#37]
This input 

https://github.com/zopyx/css-paged-media-tutorial/tree/master/lesson-basic

renders as:

[vivliostyle-output.pdf](https://github.com/vivliostyle/vivliostyle-formatter-issues/files/110778/vivliostyle-output.pdf)

(which is broken)

**Comment by kwkbtr** [comment]
Looks like a bug with floats. I will look into it.

**Comment by kwkbtr** [comment]
Fixed in 2016.7.
