### ISSUE TITLE
font-family not used in header/footer

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#38]
See the VS output here

https://www.print-css.rocks/lesson-basic.html

The text in the header and footer uses a serif fonts compared to the PDFs of the other converters although the font-family is explicitly defined for header and footer:

https://github.com/zopyx/css-paged-media-tutorial/blob/master/styles/common.css

**Comment by kwkbtr** [comment]
This is a known bug: vivliostyle/vivliostyle.js#58
We fixed this in master of the core engine, so it will be fixed in the next release of the Formatter too.

**Comment by kwkbtr** [comment]
Fixed in 2016.4 release.
