### ISSUE TITLE
2016.4: RPM supposed to work with OpenSuse Leap 42.1?

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#41]
Is the RPM supposed to work with OpenSuse?

ajung@blackmoon2:~/Downloads/vivliostyle-formatter-2016.4-rpm> sudo rpm -U vivliostyle-formatter-2016.4.x86_64.rpm 
error: Failed dependencies:
        ld-linux-x86-64.so.2()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        ld-linux-x86-64.so.2(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libX11.so.6()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libasound.so.2()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libasound.so.2(ALSA_0.9)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.14)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.3.2)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.3.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.3.4)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.4)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.6)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libc.so.6(GLIBC_2.7)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libcairo.so.2()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libcups.so.2()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libdl.so.2()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libdl.so.2(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libfreetype.so.6()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libgconf-2.so.4()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libm.so.6()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libm.so.6(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnspr4.so()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.10)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.11)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.11.1)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.12)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.12.1)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.12.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.12.4)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.2)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.4)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.6)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.7)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.8)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.9)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnss3.so(NSS_3.9.2)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnssutil3.so()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnssutil3.so(NSSUTIL_3.12)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libnssutil3.so(NSSUTIL_3.12.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpango-1.0.so.0()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpangocairo-1.0.so.0()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpthread.so.0()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpthread.so.0(GLIBC_2.12)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpthread.so.0(GLIBC_2.3.2)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libpthread.so.0(GLIBC_2.3.3)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        librt.so.1()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        librt.so.1(GLIBC_2.2.5)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libsmime3.so()(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libsmime3.so(NSS_3.10)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        libsmime3.so(NSS_3.2)(64bit) is needed by vivliostyle-formatter-2016.4-2.x86_64
        rtld(GNU_HASH) is needed by vivliostyle-formatter-2016.4-2.x86_64

However the static .tar.gz is working here.

**Comment by skoji** [comment]
Sorry, but we are not going to support OpenSUSE for the present, for the current VersaType converter users does not uses OpenSUSE.
