### ISSUE TITLE
Formatter does not support internal links

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#43]
See

https://github.com/zopyx/css-paged-media-tutorial/tree/master/lesson-pdf-links

Clicking on the internal links should not open a browser window but jump to the related position within the current PDF

**Comment by frivoal** [comment]
Hi, thanks for the report. This is a known issue, and the next release will include a fix for it.

**Comment by kwkbtr** [comment]
Fixed in 2016.7.
