### ISSUE TITLE
@page size value ignores decimal numbers

### ISSUE THREAD

**Issue by kmuto** [Trimmarks/versatype-issues#50]
```
@page {
  size: 419.528pt 595.276pt;
}
```

makes 419.00 x 595.00 pts PDF. Supporting decimal numbers is required for correct printing.

**Comment by kwkbtr** [comment]
It seems that Skia rounds the specified width and height to integers:
https://cs.chromium.org/chromium/src/third_party/skia/src/pdf/SkPDFDocument.cpp?l=217

We want to find a solution, but it will take time to resolve this.

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#432
