### ISSUE TITLE
please use CID instead of Type3

### ISSUE THREAD

**Issue by kmuto** [Trimmarks/versatype-issues#57]
(Though This is known issue for developer's team,)

When using OpenType font, current formatter creates PDF with embedded Тypе3 instead of standard CID.
Type3 has a serious problem for professional printing. It makes the file bigger and breaks text conversion. There is no warranty of the printing firm for use of Type3.

I understand that it is hard to change to using CID, but I hope to resolve it sooner.

**Comment by MurakamiShinyu** [comment]
This issue was moved to vivliostyle/vivliostyle.js#437
