### ISSUE TITLE
Hyphenation enabled by default

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#60]
The hyphenation option seems to be enabled by default (hyphens: auto).
The default behavior of all other converts is to enable hyphenation only on demand. Hyphenation should be off be default (VS 2017.2).

**Comment by MurakamiShinyu** [comment]
I agree that hyphenation should not be enabled by default, it was a mistake. We will fix this in the next release.

To cancel the current behavior, please specify `hyphens: manual` on the `body` element.

**Comment by kwkbtr** [comment]
This should be fixed in 2017.6.
