### ISSUE TITLE
Absolute path with delimiter '/' on Windows

### ISSUE THREAD

**Issue by scivola** [Trimmarks/versatype-issues#65]
Absolute paths with delimiter `/` in command-line arguments on Windows are not acceptable.

It is okay when the delimiter is a backslash `\`.

It is also okay when relative paths with delimiter `/`.

**Comment by skoji** [comment]
Path delimiter `/` is not valid for command-line arguments in Windows version( this is intended design).

> It is also okay when relative paths with delimiter `/`

So, this is an unintended behavior.
