### ISSUE TITLE
-formatter requirest X-11 display, segfaulting on headless systems

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#9]
Running vivliostyle-formatter on a headless server or without having $DISPLAY set results in a crash

```
ajung@blackmoon2:/data/home/ajung/src/vivliostyle.js/samples/adaptive-layout/apollo8> unset DISPLAY
ajung@blackmoon2:/data/home/ajung/src/vivliostyle.js/samples/adaptive-layout/apollo8> vivliostyle-formatter  index.xhtml 
Segmentation fault
```

**Comment by skoji** [comment]
version 2015.12 beta checks if X11 display is available on startup and does not segfault. 

Current version of Vivliostyle Formatter does require X11 server, so please consider to use a virtual frame buffer like Xvfb on a headless linux server. 

xvfb + vivliostyle-formatter example: 

```
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
DISPLAY=:99.0 vivliostyle-formatter http://vivliostyle.github.io/vivliostyle.js/samples/wood_chrome/index.html
```
